### ISSUE TITLE
How ?

### ISSUE THREAD

**Issue by smitthakkar96** [HackathonHackers/data#2]
Can any one post the script they used to crawl the data .

**Comment by cassidoo** [comment]
@maruthven

**Comment by maruthven** [comment]
I used pandas in python to load the CSV of the scraped data. The scripts are in this repo. 
If you're asking about how to scrape the data from Facebook, Alex Kern did that.

**Comment by kern** [comment]
I wrote `fb_scrape` to collect the data. :)

https://github.com/kern/fb_scrape
